[package]
name = "file_renamer"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["debug", "tokio"] }
regex = "1.12.2"
rfd = {version = "0.16.0" , features = ["tokio"] }
tokio = {version = "1.48.0" , features = ["fs"] }
